INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Nunc','IIF21PIW2LL',0,'Abraham Booker','08.15.14','M ','842-6991 Integer St.','09 53 74 21 13','aliquet.Proin.velit@DonecfringillaDonec.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nunc.','QOO71EXR8KT',0,'Myles Whitney','08.04.10','M ','P.O. Box 909, 9011 Metus. Rd.','05 02 36 09 82','augue@inceptoshymenaeosMauris.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('facilisis','HFJ32JDO1FJ',0,'Rajah Lang','12.18.79','M ','P.O. Box 862, 7022 Purus. St.','01 03 08 12 31','mollis.nec.cursus@et.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('libero.','LNV68VRS8RP',0,'Blake Hays','11.22.91','F','Ap #295-8480 Lacus, Road','07 61 57 83 59','Duis.at.lacus@infelisNulla.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('metus','ZZV20MTF7TK',0,'Ryan Fitzpatrick','05.05.83','M ','P.O. Box 842, 7648 Sapien Rd.','07 05 61 67 14','purus@nisimagnased.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('eget,','MAZ05TFB4MG',0,'Victor Rowland','02.27.94','M ','P.O. Box 511, 7767 Ac Rd.','02 62 45 30 28','Aliquam.vulputate.ullamcorper@fermentum.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('est','JFC00RWC2PN',0,'Isaac Bowers','03.28.05','F','341-3713 Laoreet, Av.','06 94 06 39 57','nec.euismod@Namconsequatdolor.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('sem.','HSN63XDB5KO',0,'Oren Acevedo','07.22.03','M ','Ap #848-1659 Erat St.','04 42 08 08 66','neque.sed.sem@Sed.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Quisque','VPF71CVX9HF',0,'Porter Sharpe','07.24.89','M ','451-5687 Urna. St.','08 29 37 80 61','eu.elit.Nulla@enimconsequat.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('augue','CJH60GSX8KU',0,'Vincent Francis','11.04.00','F','7266 Praesent Street','04 97 96 93 76','a.nunc@iaculisquispede.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Vivamus','XCE27BXG2FD',0,'Chaney Carpenter','05.19.84','F','P.O. Box 863, 4697 Risus Street','03 76 33 73 26','sociis@Namconsequat.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nisl','CCN15ZAW8YE',0,'Amal Hinton','12.25.88','M ','764-9662 Ipsum. Ave','01 33 82 08 93','magna.sed.dui@lectus.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('dictum.','XSO59JUW6FM',0,'Andrew Owen','08.08.13','M ','1209 Eu, Av.','05 07 78 32 32','augue.malesuada@egetmagna.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('quis,','WSW71VBX1DE',0,'Benjamin Webster','08.26.88','F','Ap #794-9721 Habitant St.','03 82 79 99 60','vel@tellus.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nisl.','VLZ60MMI1GQ',0,'Boris Frederick','04.17.08','M ','P.O. Box 416, 2370 Rutrum. Ave','09 01 18 18 43','elit@laoreetlectusquis.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('eget','TEX12HLX3UB',0,'Elvis Craig','11.27.96','F','182-8032 Eleifend, Ave','02 04 72 10 26','inceptos.hymenaeos@Nullamscelerisqueneque.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Nullam','UJG30THJ6LU',0,'Igor Burnett','01.02.85','F','384-8672 Nec Avenue','03 48 13 77 05','commodo@quis.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('molestie','WWV72ZDW4TQ',0,'Wyatt Calhoun','05.19.78','M ','366-8741 Elit, Av.','03 68 88 06 11','lacinia.Sed@sit.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('eget,','XIB60JPD5MD',0,'Abdul Sherman','08.10.96','F','P.O. Box 681, 2110 Donec Road','08 43 16 87 94','viverra.Donec.tempus@malesuadavelconvallis.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Quisque','SVO07GRT4DH',0,'Jasper Swanson','07.01.07','F','892-1613 Pellentesque Rd.','02 81 80 19 61','mauris.rhoncus.id@risus.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lacinia.','QEX27VCO0GB',0,'Kenyon Page','11.01.86','M ','8667 Leo St.','06 56 55 44 08','Fusce@molestietellusAenean.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('tortor.','UUY62CXH9JL',0,'Sebastian Garcia','08.29.09','F','249-9407 Tempor Avenue','02 41 86 00 17','tempor@mauris.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('in,','VAX16TNC4OZ',0,'Finn Meyers','06.21.91','F','568-7929 Condimentum. Road','02 57 71 33 50','iaculis.nec@pharetrafelis.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('felis,','JPK13XXU5IX',0,'Jakeem Ramos','04.27.89','M ','P.O. Box 785, 4060 Mauris St.','03 31 50 57 58','a@etliberoProin.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('auctor','PWL71TPM1DU',0,'Nathan Beach','01.02.05','M ','Ap #534-2973 Diam Rd.','08 07 21 44 24','augue.Sed.molestie@nisiMauris.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Etiam','SJL27HMP4SU',0,'Reuben Padilla','12.02.72','F','2051 Elit, Av.','07 16 24 48 62','non.dui.nec@dolorDonec.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lectus','UBF00HDQ0ST',0,'Coby Hutchinson','06.05.01','F','P.O. Box 900, 2258 Lorem Road','04 53 68 92 47','non.nisi.Aenean@elitpede.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Maecenas','GUA09RND7MR',0,'Jacob Cardenas','04.08.03','M ','5490 Nonummy Street','09 32 63 91 49','Quisque@lobortis.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Nulla','EHN06RBG2PB',0,'Barrett Prince','09.28.82','M ','Ap #269-3707 Sit Street','09 20 46 27 09','lorem@leoVivamusnibh.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('ultricies','JYS46ATJ5BL',0,'Cairo Cook','07.09.98','M ','639-3629 Vulputate, Av.','07 08 36 76 87','risus.In@blanditenim.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('auctor','UDD52NJY6EQ',0,'Davis Mccoy','03.31.85','M ','Ap #207-4239 Donec St.','07 10 26 47 56','eu.eros@loremfringilla.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('risus.','QUO29BPX9BU',0,'Connor Gaines','11.19.76','F','811-2025 Et Road','04 26 41 69 47','in.lobortis@augueeutempor.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('eleifend,','UGB05SRA9OJ',0,'Raphael Maldonado','10.14.86','F','P.O. Box 308, 9590 Eu, Street','01 41 68 38 94','Aliquam@Donecelementumlorem.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('gravida.','COM24ZPF7TP',0,'Julian Lewis','08.23.83','F','P.O. Box 489, 1756 Molestie Av.','07 08 22 13 27','tincidunt.orci@ultricesiaculis.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nulla','QZG76EYH4AY',0,'Raja Castaneda','11.15.95','M ','P.O. Box 512, 2876 Sed Avenue','09 12 42 97 99','quis@leo.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('suscipit','SCF04IOA4UB',0,'Jelani Finch','11.14.78','F','Ap #388-3842 Dolor. Avenue','02 67 78 88 33','dui.Suspendisse@eumetusIn.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('ipsum.','OPB52ZRG3OQ',0,'Octavius Colon','02.23.90','F','6632 Orci Street','04 87 97 07 80','ridiculus.mus@condimentumDonecat.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('quam,','TIO28WMA4BZ',0,'Elton Martin','06.08.83','M ','7693 Ligula Rd.','02 98 86 66 57','turpis.vitae@enimnon.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('sem','LZT34JYP9NT',0,'Reese Herring','08.04.83','M ','Ap #170-2555 Ultrices St.','03 97 80 05 86','iaculis.quis@dolorsit.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('enim','RZR16CZR9FI',0,'Zeph Mcclure','09.26.88','F','2839 Consectetuer Rd.','09 03 53 16 33','lorem@pretiumaliquetmetus.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('consectetuer','MTQ39JZX3EF',0,'Uriah Pruitt','02.20.05','M ','P.O. Box 243, 6125 Nulla Av.','08 64 70 61 74','orci.tincidunt.adipiscing@molestie.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('et','YFR80QNK3ZG',0,'Lamar Cunningham','01.01.84','F','Ap #508-2431 Nisi. Road','06 43 61 26 03','elit.Curabitur@ornare.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('iaculis','IGS22QKO5CE',0,'Kirk Atkinson','01.13.07','F','P.O. Box 137, 8504 Ac Avenue','03 35 89 97 19','in.faucibus.orci@erosProin.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Cras','ICP76TXM0XF',0,'Chadwick Ortega','11.04.72','M ','999-3475 Vulputate Avenue','02 18 51 12 15','nisi@doloregestasrhoncus.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('dolor','ONA09YPE6UI',0,'Quentin Willis','02.02.04','F','4254 Venenatis St.','09 06 23 46 58','nascetur@sollicitudinadipiscingligula.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('metus','PGH14ICF0NH',0,'Victor Morrow','09.21.85','M ','Ap #690-2799 Lorem, Street','01 80 63 14 08','orci.lobortis@nibhQuisquenonummy.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('ornare','GWG96LWA3NE',0,'Nolan Clayton','10.29.12','M ','2971 Ut Ave','03 66 38 71 10','vestibulum.lorem.sit@mollis.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('pellentesque','GJX84LKO6ZZ',0,'Abbot Christian','12.18.94','M ','5003 Eget, Street','03 90 86 60 85','natoque.penatibus.et@neque.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lectus','YDH80RWV0PU',0,'Todd Joyce','04.30.83','M ','265-1489 Aliquam St.','07 49 35 98 48','fermentum.vel@etnetuset.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nonummy','UHL55OYZ5AZ',0,'Harrison Faulkner','09.08.85','M ','P.O. Box 258, 4628 Placerat Avenue','05 28 26 67 40','Cras@Praesentluctus.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nulla','XAX52PXE6CK',0,'Allen Barrett','01.16.89','M ','8261 Vulputate Avenue','05 69 37 46 40','Fusce.mi.lorem@ipsumdolor.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('felis','OHP55AKU3JC',0,'Michael Swanson','11.27.13','F','6925 Et Road','04 19 99 78 10','In.at.pede@Sednunc.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('ultrices','VAK15EIF6NZ',0,'Graham Hughes','10.21.73','F','Ap #273-7770 Pulvinar Street','06 82 98 45 28','ligula@eleifendegestas.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Nam','TWC94FRT8MS',0,'Valentine Vazquez','12.29.10','F','550-3609 Risus Road','01 86 78 89 03','sit.amet.nulla@posuereenim.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('pharetra','TMI05PWK6RW',0,'Quamar Marks','09.24.08','F','Ap #831-9243 Aenean St.','09 83 43 69 64','nibh@Morbisitamet.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Duis','FHP85VMX6BE',0,'Acton Carver','11.13.78','M ','5144 Morbi Rd.','04 20 74 06 00','nec.mauris@scelerisquenequeNullam.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('et','COY52RRI6OH',0,'David Stevens','04.19.07','F','Ap #973-7326 Donec St.','05 44 76 54 33','fringilla.ornare@velit.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('a,','NMJ65XDN1HN',0,'Kuame Walls','01.16.74','M ','2342 Et, Street','05 41 98 87 27','ultrices.Vivamus@miloremvehicula.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lobortis','KZM54NYU8VX',0,'Xenos Woodward','04.28.84','M ','398-1802 Nullam Rd.','01 74 06 14 58','lectus@necmalesuada.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('tellus.','KTT59KNN3AU',0,'Hoyt Meyers','01.24.89','M ','P.O. Box 830, 5360 Etiam Rd.','08 04 55 22 76','Vestibulum.ut.eros@orci.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('ut','SGY77HSA2KK',0,'Jacob Holman','03.19.84','F','Ap #173-1315 Vestibulum Av.','05 11 00 80 22','sodales@conguea.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nibh.','LPM67ADL0DB',0,'Tobias Knapp','01.16.11','F','Ap #410-2335 Eu St.','04 44 78 17 60','semper.et@vehiculaPellentesque.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('metus','OTK64KDV5ST',0,'Ryder Faulkner','05.24.98','F','466-1547 Et Av.','07 44 41 65 15','blandit@vestibulum.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('ac','YRZ85ELM0IF',0,'Kaseem Randolph','11.09.95','M ','P.O. Box 686, 4006 Auctor St.','04 56 80 08 81','augue.malesuada.malesuada@idblandit.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lacus.','DFG93KUJ2LU',0,'Yasir Atkinson','03.14.94','M ','Ap #993-6510 Tincidunt Rd.','06 90 67 99 35','enim@sagittislobortismauris.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nec','TEA12TDO2WJ',0,'Jamal Crane','12.11.85','M ','980-263 In Ave','04 11 83 23 01','dui@pellentesquea.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('enim','OOE94RTO7EH',0,'Ian Bradshaw','10.22.10','M ','413-4848 Aliquam Road','08 46 06 83 98','tempor.diam@nonummy.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('eget','TKE56UZM4MY',0,'Benedict Lamb','03.10.95','M ','P.O. Box 374, 7527 Dapibus Avenue','09 63 76 00 96','Nunc.quis.arcu@Quisquenonummyipsum.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Curabitur','OQB23KRB0MD',0,'Lawrence Edwards','06.01.12','F','P.O. Box 263, 8801 Phasellus Road','08 51 02 83 80','nec@sapien.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('et','CPQ48VQB5JQ',0,'Maxwell Zamora','06.25.82','M ','9956 Adipiscing, St.','04 68 82 17 93','non.lacinia@Sed.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Class','TGH80KGC1KM',0,'Jamal Oconnor','02.09.08','F','537-7271 Urna. St.','07 80 24 08 33','Duis.cursus@nonfeugiat.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('risus.','EEC00TQD1YU',0,'Edan Small','06.22.88','F','925-6724 Lacus. St.','01 85 78 36 12','malesuada.vel.venenatis@gravidanuncsed.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Cum','FCM04ACA5YL',0,'Forrest Wallace','08.10.96','M ','Ap #700-9810 A Street','01 96 96 12 11','Proin@nonquamPellentesque.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('aliquam','RSW22XCG4WX',0,'Hashim Byrd','05.26.03','F','8425 Et, Ave','02 90 57 02 95','tortor.dictum.eu@aarcu.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nunc','FAS98STY1NV',0,'Kyle Pugh','03.20.08','M ','Ap #881-6332 Eu Street','03 68 80 29 22','hendrerit.neque.In@acfacilisis.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('adipiscing','ECU60RDT0EZ',0,'Reese Oconnor','02.15.05','F','3002 Semper Rd.','01 66 03 50 57','odio@ametluctus.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('est','YQO13ZPX3IH',0,'Demetrius Strickland','01.10.03','F','P.O. Box 919, 8773 Mollis Ave','06 95 97 86 65','tristique.neque.venenatis@Donecfelis.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('justo','IXY23BHT0ZE',0,'Cadman Franco','09.23.09','M ','P.O. Box 995, 9479 Duis Avenue','05 62 59 84 43','Duis@idmagna.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Donec','GRL79LLW8XN',0,'Cade Colon','05.09.86','M ','Ap #693-3073 Luctus Road','09 70 18 77 16','a.odio.semper@quispede.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lacus.','JPE69YEL8OC',0,'Steel Brock','01.17.00','M ','914-3192 Vel Ave','05 43 09 26 35','viverra.Maecenas@facilisislorem.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('sit','TUC77CYO1YW',0,'Keith Schultz','05.27.72','M ','248-5837 Laoreet Avenue','03 16 84 40 84','consectetuer@ullamcorpermagna.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('elit','ULQ07YRJ4HV',0,'Lane Welch','12.06.94','M ','288-8008 Vitae Street','05 88 21 06 85','convallis.in.cursus@scelerisquesedsapien.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('bibendum','EVM59SON4ST',0,'Orlando Whitley','06.16.00','F','Ap #958-2686 In Avenue','07 59 38 46 51','faucibus.orci@laoreet.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('velit','XOE06TXA8AR',0,'Stuart Walls','04.05.05','M ','P.O. Box 155, 5990 A Ave','08 25 00 30 17','nec.cursus.a@dictumaugue.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nisl.','TKI38DSS4TZ',0,'Hilel Robles','11.23.06','M ','P.O. Box 692, 4503 Adipiscing Rd.','03 85 47 34 16','mi.pede.nonummy@Naminterdum.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('fringilla','QWO70TXV8PF',0,'Noah Nielsen','08.03.97','M ','1526 Lacus. St.','08 19 81 61 96','sed.tortor.Integer@CraspellentesqueSed.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Proin','MBB11NDZ9QW',0,'August Garrett','08.29.74','M ','2513 Dolor, Rd.','09 41 27 26 29','senectus@est.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('amet,','QAP76XPB9XT',0,'Emerson Hartman','08.30.74','F','9378 Nulla Rd.','09 74 28 57 56','Quisque@magna.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Duis','HBD93PBE2JB',0,'Tarik Vincent','01.17.94','F','8771 Cursus Ave','02 63 85 48 13','arcu.Aliquam.ultrices@gravidamolestie.com');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('dis','BDA06ZRJ5VV',0,'Beau Mann','04.29.77','F','2654 Blandit. Avenue','09 46 00 86 89','dictum@vitae.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('nec','JRY89IHC2JE',0,'Abbot Burks','05.23.01','F','P.O. Box 532, 8954 Id, Avenue','03 07 39 99 93','vulputate@molestiesodales.net');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('convallis','WYJ55RGV1SK',0,'Elvis Albert','01.02.85','F','P.O. Box 901, 6905 Cursus Avenue','04 69 85 64 29','Aliquam@liberoatauctor.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('Praesent','PXN17SWS5EL',0,'Hamish Rowe','01.15.74','F','442-4824 Sagittis Road','04 24 89 66 32','ac.tellus.Suspendisse@auctor.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('a,','EDG38TIB7NB',0,'Guy Benton','11.10.93','F','420-9428 Aenean Av.','06 21 77 16 71','nunc.nulla.vulputate@tristique.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('blandit','VDP07IWI9JP',0,'Malcolm Fry','10.11.73','F','3335 In Avenue','04 17 31 64 36','sem.ut.cursus@Vestibulumante.co.uk');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('urna,','HUN00CUI0NL',0,'Tyler Chavez','08.31.77','M ','7719 Magna Rd.','09 80 92 84 83','luctus.felis.purus@Maecenas.org');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('massa.','JBA32NUI4GV',0,'Francis Hess','01.03.86','F','P.O. Box 999, 3615 Laoreet Avenue','02 23 45 96 18','malesuada@Phasellus.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('metus.','LEX99DLR8GK',0,'Charles Moore','01.09.84','M ','6255 Nisi Rd.','02 90 53 31 43','nunc.ac.mattis@commodotinciduntnibh.ca');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('lorem.','UGZ86YOC1JE',0,'Chaney Dillon','05.02.07','M ','Ap #147-508 Integer Street','04 59 87 31 78','ut.nulla.Cras@Nulla.edu');
INSERT INTO Users (Username,Password,Admin,Nome,DNascimento,Genero,Morada,Telefone,Email) VALUES ('dictum','CZY89JTJ8BL',0,'Lucas Duffy','12.25.89','M ','P.O. Box 381, 8272 Nec, St.','02 63 35 43 13','est.ac.facilisis@egetvolutpatornare.com');


INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('et nunc.','laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis.','04.12.15','11.30.15',66);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('id, erat. Etiam','blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate','04.14.15','01.10.17',68);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Integer in','eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec','04.18.15','02.25.17',31);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('dictum eleifend,','mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus','04.22.15','08.25.15',73);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('imperdiet ornare. In','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor','04.22.15','02.24.17',59);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('lobortis quam a','amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient','04.20.15','08.18.15',23);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Ut','porta elit, a feugiat','04.16.15','08.15.15',52);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ornare. Fusce mollis.','tortor at risus. Nunc ac sem ut dolor dapibus','04.22.15','12.18.15',75);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Cras convallis','ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec','04.18.15','05.24.16',82);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('scelerisque sed,','Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.','04.11.15','06.13.16',27);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('vel,','blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed','04.21.15','05.31.16',89);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ipsum','cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris','04.16.15','02.28.17',78);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eros turpis non','porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget,','04.11.15','03.04.16',14);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('luctus vulputate, nisi','Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque,','04.14.15','09.07.16',80);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('convallis est, vitae','aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas','04.17.15','03.01.16',61);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Aenean','mauris ipsum','04.16.15','10.08.16',55);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('non','fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed','04.12.15','12.17.15',51);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('magna','non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum','04.11.15','03.12.17',28);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('fringilla mi lacinia','Curabitur consequat,','04.11.15','05.17.16',52);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('vestibulum, neque','a, magna. Lorem ipsum dolor sit','04.18.15','01.16.16',25);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eros nec','Cras eget','04.21.15','01.26.16',23);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('orci. Ut','Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum','04.13.15','11.16.16',8);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('parturient','Nam porttitor scelerisque neque. Nullam nisl. Maecenas','04.19.15','03.11.17',57);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ligula. Aenean gravida','hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus.','04.20.15','02.09.17',10);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('neque. Sed','tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit','04.15.15','02.19.16',29);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('arcu eu odio','dolor, tempus non, lacinia at,','04.15.15','06.12.16',51);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Quisque varius.','purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam','04.14.15','01.24.16',29);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ridiculus','Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec','04.11.15','11.09.16',86);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('consequat dolor','erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc','04.16.15','10.24.16',70);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('augue porttitor','Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.','04.18.15','11.28.16',66);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('et malesuada fames','vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse','04.16.15','08.13.16',80);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('magna tellus faucibus','rhoncus. Donec est. Nunc ullamcorper, velit','04.18.15','02.16.17',55);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('magna.','non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate','04.16.15','12.14.16',36);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eu','lorem semper auctor. Mauris vel turpis. Aliquam','04.11.15','03.16.16',11);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Curabitur egestas','lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus','04.09.15','08.28.15',75);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('risus. Nunc','sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit','04.19.15','12.19.15',36);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('elit','purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices.','04.14.15','07.15.16',33);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Nullam','quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui.','04.08.15','12.20.16',18);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('commodo','Donec egestas. Aliquam nec enim. Nunc','04.15.15','01.21.16',36);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('consequat dolor','arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,','04.18.15','02.29.16',22);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('congue','et netus et','04.12.15','09.29.16',11);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('fermentum metus. Aenean','lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet','04.18.15','10.09.15',51);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ligula.','purus. Maecenas libero est, congue a, aliquet vel, vulputate eu,','04.14.15','02.16.17',58);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('odio a purus.','vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet,','04.16.15','08.19.16',64);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('purus, accumsan interdum','Cum sociis natoque penatibus et','04.13.15','04.24.16',58);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Aliquam erat','Duis sit amet diam eu dolor egestas rhoncus.','04.18.15','01.06.16',90);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Morbi quis urna.','tellus. Nunc lectus','04.08.15','03.30.17',34);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('non','ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.','04.09.15','04.21.16',70);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('sit','consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras','04.13.15','04.14.17',11);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('rhoncus. Proin nisl','enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim','04.18.15','04.03.16',54);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Sed nec','ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc','04.11.15','01.06.16',47);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Aliquam','blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante','04.21.15','04.11.17',8);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Donec non justo.','nisl sem, consequat nec, mollis vitae, posuere','04.13.15','01.13.16',71);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Fusce','gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio.','04.12.15','05.03.16',16);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('nisi nibh lacinia','sem. Nulla','04.12.15','10.01.15',27);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Vivamus nisi. Mauris','pede ac urna. Ut tincidunt vehicula risus.','04.14.15','12.02.16',19);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ante','nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam','04.12.15','10.11.15',78);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('In','nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique','04.15.15','03.19.17',58);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('volutpat','Quisque libero','04.09.15','12.06.15',37);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('viverra.','ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis','04.12.15','07.01.16',83);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('dolor, tempus non,','arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut,','04.17.15','10.23.15',40);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('metus. Aliquam','dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.','04.14.15','11.06.16',44);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('sapien. Cras dolor','adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius','04.15.15','02.19.16',29);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eu turpis.','nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu','04.14.15','03.28.17',54);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('non, egestas a,','laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus.','04.11.15','06.14.16',66);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('a purus. Duis','Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis','04.09.15','03.07.16',59);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('mi enim, condimentum','egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu','04.12.15','12.21.15',62);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('fringilla. Donec feugiat','at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes,','04.15.15','03.15.16',66);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('erat,','lacus, varius','04.19.15','12.18.16',54);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('dignissim.','ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In','04.16.15','06.03.16',16);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('sociis','rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,','04.12.15','05.01.16',48);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('quis','at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc','04.14.15','09.17.16',71);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('purus, accumsan interdum','turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut','04.13.15','09.04.15',66);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('tristique senectus et','ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam','04.19.15','09.04.16',74);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Nulla eget','molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero','04.11.15','12.12.15',33);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eget mollis lectus','lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a','04.12.15','04.07.16',87);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('euismod est arcu','scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames','04.22.15','12.15.15',72);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('enim non nisi.','eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae','04.11.15','03.02.17',30);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('ultrices. Duis volutpat','a feugiat tellus lorem eu metus. In lorem. Donec elementum,','04.20.15','02.04.16',14);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('sed','quam dignissim pharetra.','04.13.15','01.29.16',67);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('tempus eu,','semper. Nam tempor diam dictum sapien.','04.19.15','01.08.17',34);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('vitae','Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque','04.19.15','11.05.15',36);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('libero est, congue','adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus,','04.11.15','05.26.16',18);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('lorem. Donec elementum,','ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;','04.17.15','08.29.15',43);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('gravida.','penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec','04.11.15','07.09.16',75);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Nunc','tincidunt adipiscing. Mauris molestie','04.12.15','02.24.17',58);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('pharetra. Nam','Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc','04.17.15','12.19.16',51);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('lorem','Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit','04.10.15','08.17.16',59);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('bibendum. Donec felis','arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum','04.13.15','11.05.15',15);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('Vivamus molestie dapibus','Nam interdum enim non nisi. Aenean eget metus. In nec','04.09.15','03.20.17',37);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('convallis,','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin','04.14.15','11.12.16',63);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('sit amet metus.','Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.','04.18.15','02.21.17',14);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('est. Mauris eu','dolor, nonummy ac, feugiat non, lobortis quis, pede.','04.12.15','06.18.16',29);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('nisi. Mauris nulla.','ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum','04.09.15','10.06.15',31);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('et arcu imperdiet','id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent','04.19.15','10.09.16',25);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('adipiscing ligula.','Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer','04.15.15','01.15.16',6);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('imperdiet ullamcorper.','In tincidunt congue','04.14.15','07.29.16',51);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eu augue porttitor','tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi','04.17.15','03.01.17',8);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('eu sem. Pellentesque','Class aptent taciti sociosqu ad litora torquent per conubia nostra, per','04.15.15','08.31.16',22);
INSERT INTO projeto (nomeproj,obs,dcriacao,dfinalprojeto,idmaster) VALUES ('dis parturient montes,','Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros','04.11.15','12.14.15',76);


INSERT INTO categoria (nomecat,idprojeto) VALUES ('ut',20);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('id,',70);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nonummy.',26);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('sapien',67);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('mi,',13);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('ac',53);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('ante bibendum',93);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('adipiscing,',26);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('euismod mauris',21);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('diam',25);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('arcu. Vestibulum',14);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Pellentesque',80);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('senectus',18);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('tincidunt dui',41);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Mauris eu',78);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('porta',98);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Quisque',18);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('iaculis nec,',99);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('lobortis',33);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('at augue',83);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('semper',63);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('torquent per',27);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('interdum',37);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('eget, venenatis',56);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('a,',30);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Aliquam',36);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('ut',62);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('accumsan',72);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('laoreet, libero',22);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Donec porttitor',75);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nulla',77);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('varius et,',12);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('commodo hendrerit.',61);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('vitae diam.',94);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nec,',87);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('ornare,',75);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Donec est.',26);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('dapibus',19);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Integer',55);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('lectus.',106);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('parturient montes,',88);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('faucibus orci',77);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('egestas a,',85);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('at,',61);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Donec',69);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('magna et',79);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('lobortis,',48);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('lobortis',55);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('enim',88);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('luctus.',48);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('rutrum urna,',75);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Nullam',22);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('egestas',42);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('turpis.',83);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('quam',102);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('ultricies',15);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('fringilla,',84);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('orci.',12);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('cursus',15);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('erat eget',69);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('dui',92);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nec',50);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('risus. Donec',106);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('rutrum urna,',16);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('semper,',101);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Nunc sed',91);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('tincidunt,',66);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('Sed dictum.',63);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nibh.',44);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('auctor vitae,',90);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('amet ultricies',48);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('non sapien',94);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('mi, ac',91);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nec',12);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('congue',76);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('malesuada vel,',75);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('justo nec',38);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('ut cursus',21);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('habitant',68);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('laoreet,',97);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('pede, malesuada',16);
INSERT INTO categoria (nomecat,idprojeto) VALUES ('nec tempus',92);


INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'rhoncus. Nullam','04.29.15','05.19.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'dictum. Proin','04.29.15','07.17.16','Execucao','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'semper egestas,','04.29.15','04.30.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'Proin eget','04.29.15','04.13.16','Execucao','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (9,54,'sollicitudin a,','04.29.15','04.22.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (9,54,'Proin mi.','04.29.15','04.21.16','Execucao','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'dis parturient','04.29.15','04.29.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (9,54,'Morbi non','04.29.15','05.01.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (9,54,'elementum purus,','04.29.15','08.06.16','Execucao','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (9,54,'feugiat placerat','04.29.15','08.04.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'convallis est,','04.29.15','05.02.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (78,54,'euismod ac,','04.29.15','04.27.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (9,54,'sem molestie','04.29.15','05.31.16','Concluida','Criada');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'metus. In','04.29.15','05.13.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,24,'et magnis','04.29.15','07.16.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'Duis volutpat','04.29.15','06.24.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,24,'ac mattis','04.29.15','07.10.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'ante, iaculis','04.29.15','05.28.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'vestibulum. Mauris','04.29.15','08.15.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'elit. Aliquam','04.29.15','04.25.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'nonummy ut,','04.29.15','04.19.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,24,'enim nec','04.29.15','04.30.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,24,'facilisis lorem','04.29.15','05.02.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'faucibus ut,','04.29.15','08.20.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,24,'magna tellus','04.29.15','06.21.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa) VALUES (28,10,'eros. Proin','04.29.15','06.11.16','Execucao','Sugerida');
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'enim. Mauris','04.29.15','08.18.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'Aliquam gravida','04.29.15','06.01.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'orci, consectetuer','04.29.15','05.06.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'mauris sapien,','04.29.15','06.12.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'ut aliquam','04.29.15','07.25.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'Vivamus nibh','04.29.15','06.08.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'ligula consectetuer','04.29.15','06.27.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'sit amet','04.29.15','04.13.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'in, tempus','04.29.15','07.08.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'eu dui.','04.29.15','04.28.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'aliquet vel,','04.29.15','06.01.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'Sed nulla','04.29.15','07.03.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'blandit congue.','04.29.15','06.24.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'nec, euismod','04.29.15','04.14.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'litora torquent','04.29.15','04.26.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'congue a,','04.29.15','08.22.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'euismod urna.','04.29.15','04.27.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'nec luctus','04.29.15','05.15.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'non magna.','04.29.15','07.13.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'nibh vulputate','04.29.15','07.26.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'ut cursus','04.29.15','07.26.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'at, velit.','04.29.15','06.05.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'vulputate velit','04.29.15','08.10.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'adipiscing elit.','04.29.15','06.25.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'Ut nec','04.29.15','06.08.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'tempus non,','04.29.15','05.08.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'quis turpis','04.29.15','05.23.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'Cras pellentesque.','04.29.15','04.18.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'tempus scelerisque,','04.29.15','08.16.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'felis eget','04.29.15','06.14.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'mollis lectus','04.29.15','08.20.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'aliquet. Proin','04.29.15','05.04.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'consequat nec,','04.29.15','06.16.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'eu arcu.','04.29.15','07.02.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'erat semper','04.29.15','05.29.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'ut aliquam','04.29.15','06.11.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (49,47,'Maecenas libero','04.29.15','04.21.16','Execucao','Rejeitada',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'nonummy ac,','04.29.15','06.02.16','Execucao','Aceite',88);
INSERT INTO tarefa (idcategoria,idcriador,nometarefa,dcriacao,dfinal,estadotarefa,tipotarefa,idaceitepor) VALUES (41,47,'et ipsum','04.29.15','06.13.16','Execucao','Rejeitada',88);

INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (54,15);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (54,9);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (54,10);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (54,12);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (54,16);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (54,6);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,29);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,28);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,23);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (24,27);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,22);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,19);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (24,28);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (24,23);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (24,29);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (24,24);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,27);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (10,26);
INSERT INTO useralocadotarefa (iduser,idtarefa) VALUES (24,19);


INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (55,19,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (90,69,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (82,50,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (47,6,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (21,54,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (31,27,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (48,19,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (29,82,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (86,54,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (74,71,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (74,37,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (68,70,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (76,36,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (42,44,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (72,10,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (25,79,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (42,13,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (78,70,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (36,60,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (83,42,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (87,21,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (53,50,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (45,82,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (55,83,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (67,58,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (85,55,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (39,50,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (66,44,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (49,74,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (39,81,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (72,24,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (39,53,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (51,27,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (70,75,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (61,62,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (63,7,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (40,32,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (88,88,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (29,34,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (66,50,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (71,78,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (50,39,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (79,48,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (78,35,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (58,82,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (88,47,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (39,61,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (27,80,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (81,88,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (45,84,'Coordenador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (23,70,'Colaborador');
INSERT INTO papel (idprojeto,iduser,funcaoproj) VALUES (81,31,'Coordenador');



INSERT INTO contactos (iduser,contacto) VALUES (7,10);
INSERT INTO contactos (iduser,contacto) VALUES (9,69);
INSERT INTO contactos (iduser,contacto) VALUES (10,42);
INSERT INTO contactos (iduser,contacto) VALUES (29,59);
INSERT INTO contactos (iduser,contacto) VALUES (14,53);
INSERT INTO contactos (iduser,contacto) VALUES (14,45);
INSERT INTO contactos (iduser,contacto) VALUES (29,31);
INSERT INTO contactos (iduser,contacto) VALUES (22,20);
INSERT INTO contactos (iduser,contacto) VALUES (24,67);
INSERT INTO contactos (iduser,contacto) VALUES (12,7);
INSERT INTO contactos (iduser,contacto) VALUES (15,86);
INSERT INTO contactos (iduser,contacto) VALUES (10,40);
INSERT INTO contactos (iduser,contacto) VALUES (26,27);
INSERT INTO contactos (iduser,contacto) VALUES (8,90);
INSERT INTO contactos (iduser,contacto) VALUES (19,48);
INSERT INTO contactos (iduser,contacto) VALUES (17,74);
INSERT INTO contactos (iduser,contacto) VALUES (30,84);
INSERT INTO contactos (iduser,contacto) VALUES (28,51);
INSERT INTO contactos (iduser,contacto) VALUES (19,73);
INSERT INTO contactos (iduser,contacto) VALUES (17,19);
INSERT INTO contactos (iduser,contacto) VALUES (22,75);
INSERT INTO contactos (iduser,contacto) VALUES (6,46);
INSERT INTO contactos (iduser,contacto) VALUES (13,21);
INSERT INTO contactos (iduser,contacto) VALUES (29,56);
INSERT INTO contactos (iduser,contacto) VALUES (15,44);
INSERT INTO contactos (iduser,contacto) VALUES (7,65);
INSERT INTO contactos (iduser,contacto) VALUES (23,78);
INSERT INTO contactos (iduser,contacto) VALUES (24,51);
INSERT INTO contactos (iduser,contacto) VALUES (7,56);
INSERT INTO contactos (iduser,contacto) VALUES (24,59);
INSERT INTO contactos (iduser,contacto) VALUES (22,64);
INSERT INTO contactos (iduser,contacto) VALUES (14,68);
INSERT INTO contactos (iduser,contacto) VALUES (19,51);
INSERT INTO contactos (iduser,contacto) VALUES (7,52);
INSERT INTO contactos (iduser,contacto) VALUES (15,45);
INSERT INTO contactos (iduser,contacto) VALUES (21,9);
INSERT INTO contactos (iduser,contacto) VALUES (21,86);
INSERT INTO contactos (iduser,contacto) VALUES (16,83);
INSERT INTO contactos (iduser,contacto) VALUES (16,42);
INSERT INTO contactos (iduser,contacto) VALUES (18,83);
INSERT INTO contactos (iduser,contacto) VALUES (23,57);
INSERT INTO contactos (iduser,contacto) VALUES (23,87);
INSERT INTO contactos (iduser,contacto) VALUES (26,42);
INSERT INTO contactos (iduser,contacto) VALUES (17,59);
INSERT INTO contactos (iduser,contacto) VALUES (12,10);
INSERT INTO contactos (iduser,contacto) VALUES (19,56);
INSERT INTO contactos (iduser,contacto) VALUES (14,29);
INSERT INTO contactos (iduser,contacto) VALUES (17,12);
INSERT INTO contactos (iduser,contacto) VALUES (24,64);
INSERT INTO contactos (iduser,contacto) VALUES (17,42);
INSERT INTO contactos (iduser,contacto) VALUES (17,62);
INSERT INTO contactos (iduser,contacto) VALUES (16,71);
INSERT INTO contactos (iduser,contacto) VALUES (21,14);
INSERT INTO contactos (iduser,contacto) VALUES (8,38);
INSERT INTO contactos (iduser,contacto) VALUES (11,61);
INSERT INTO contactos (iduser,contacto) VALUES (23,90);


INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'vehicula','pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'consectetuer','Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'placerat,','eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque',44);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'Vivamus','at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'enim','metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'mollis','Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae',44);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'quam','nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'sit','et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'Vivamus','neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'Nunc','ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam.',44);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'ornare,','rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'ligula','Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin',44);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'Nulla','a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut,',44);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'aliquet','Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'ut,','bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'Mauris','porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (66,'in,','convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'ridiculus','ridiculus mus. Proin vel arcu eu odio tristique pharetra.',81);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'neque.','lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'in','pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'aliquet','euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl',81);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'amet,','neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus.',53);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'Integer','interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed,',81);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'consectetuer','arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id,',61);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'Morbi','accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'penatibus','nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus.',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'odio','posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed',81);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'Curabitur','eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed',53);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'bibendum','vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non,',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'iaculis','ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut',50);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'vestibulum','lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus',61);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'mattis','Curabitur vel lectus. Cum sociis natoque penatibus',61);
INSERT INTO topico (idprojeto,nometopico,descricao,idcriador) VALUES (39,'vestibulum','Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut',53);


INSERT INTO resposta (idtopico,texto,iduser) VALUES (21,'luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (19,'Mauris vel turpis. Aliquam adipiscing lobortis risus. In',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (10,'ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (20,'dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (8,'Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (18,'diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit.',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (17,'nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (16,'egestas. Aliquam fringilla cursus purus.',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (14,'parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (8,'vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (18,'at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (14,'nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (20,'tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (20,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan interdum',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (24,'vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla.',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (14,'cursus purus. Nullam scelerisque neque sed',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (21,'id risus quis diam',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (10,'euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus',44);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (12,'Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (39,'neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna,',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (36,'Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (30,'sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (39,'diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus.',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (39,'a, dui. Cras pellentesque. Sed dictum. Proin',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (29,'id, libero. Donec consectetuer mauris id sapien.',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (40,'est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (31,'risus. Nulla eget metus eu',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (39,'vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (35,'lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim',61);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (28,'et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (31,'fermentum vel, mauris. Integer sem elit, pharetra',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (29,'Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui,',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (38,'augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (37,'sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (30,'vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula.',61);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (28,'rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra.',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (25,'Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (25,'vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui.',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (32,'et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (25,'ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (38,'sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla',61);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (25,'a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce',61);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (40,'Aliquam ultrices iaculis odio. Nam interdum enim',61);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (40,'Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (27,'vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (37,'facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel,',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (27,'id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (34,'sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit',50);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (28,'adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus',61);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (26,'semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula',53);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (36,'gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce',81);
INSERT INTO resposta (idtopico,texto,iduser) VALUES (35,'et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam',61);




